POST http://localhost:8080/meeting/create HTTP/1.1
content-type: application/json

{
  "meetingName": "hacku00",
  "meetingStartTime": "2022/03/06 10:33:00",
  "presenters": [
    "test01",
    "koki1998"
  ]
}